# Generated by Django 3.2.13 on 2022-07-19 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='escrow_payment',
            new_name='withdrawal',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='purpose',
        ),
        migrations.AddField(
            model_name='payment',
            name='reason_payment',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
