<<<<<<< HEAD
# Generated by Django 3.2.13 on 2022-12-08 05:40
=======
# Generated by Django 3.2.13 on 2022-09-19 21:56
>>>>>>> 4f236226881f5ca1e6b8b1d3c212ad56d3e96d0b

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0002_alter_payment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='user',
<<<<<<< HEAD
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.user'),
=======
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mainapp.user'),
            preserve_default=False,
>>>>>>> 4f236226881f5ca1e6b8b1d3c212ad56d3e96d0b
        ),
    ]
