# Generated by Django 3.2.13 on 2022-07-19 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0056_billingpayment'),
        ('payments', '0002_auto_20220719_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.onlinelesson'),
        ),
    ]
