# Generated by Django 3.2.7 on 2022-01-25 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quater',
            name='town',
        ),
    ]
