# Generated by Django 3.2.6 on 2021-08-08 06:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('location', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('phone_number', models.CharField(max_length=15)),
                ('profile_pic', models.ImageField(upload_to='profile_img')),
                ('is_tutor', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TutorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_of_education', models.CharField(choices=[('Bachelor Degree(Bac +3)', 'Bachelor Degree'), ('Master Degree(Bac +5)', 'Master Degree'), ('Advanced Level(Bac)', 'Advanced Level'), ('Doctorate', 'Doctorate'), ('HND', 'HND'), ('Others', 'Others')], max_length=50)),
                ('bio', models.TextField(blank=True, null=True)),
                ('target', models.CharField(choices=[('Nursery', 'Nursery'), ('Primary', 'Primary'), ('Secondary', 'Secondary'), ('High School', 'High School'), ('University', 'University'), ('Others', 'Others')], max_length=40)),
                ('charge_rate', models.CharField(choices=[('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('Hourly', 'Hourly')], max_length=40)),
                ('amount', models.IntegerField()),
                ('category', models.ManyToManyField(to='category.Category')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.city')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.country')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mainapp.profile')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.region')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.section')),
                ('sub_category', models.ManyToManyField(to='category.SubCategory')),
            ],
        ),
    ]
