# Generated by Django 3.2.6 on 2021-08-08 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorprofile',
            name='quater',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
