# Generated by Django 3.2.6 on 2021-08-08 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
        ('mainapp', '0002_tutorprofile_quater'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorprofile',
            name='country',
            field=models.ForeignKey(default='Cameroon', on_delete=django.db.models.deletion.CASCADE, to='location.country'),
        ),
    ]
