# Generated by Django 3.2.7 on 2021-10-24 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_searchhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchhistory',
            name='account_type',
        ),
        migrations.RemoveField(
            model_name='searchhistory',
            name='category',
        ),
        migrations.RemoveField(
            model_name='searchhistory',
            name='charge',
        ),
        migrations.RemoveField(
            model_name='searchhistory',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='searchhistory',
            name='region',
        ),
        migrations.RemoveField(
            model_name='searchhistory',
            name='result',
        ),
        migrations.RemoveField(
            model_name='searchhistory',
            name='subcategory',
        ),
        migrations.RemoveField(
            model_name='searchhistory',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='searchhistory',
            name='town',
        ),
        migrations.RemoveField(
            model_name='searchhistory',
            name='user',
        ),
    ]
