# Generated by Django 3.2.7 on 2021-10-24 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20211025_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchhistory',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
