# Generated by Django 3.2.7 on 2021-11-06 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_alter_searchhistory_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='howtouse',
            name='how_description',
            field=models.TextField(default='how to used'),
        ),
    ]
