# Generated by Django 3.2.7 on 2021-11-07 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_howtouse_how_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verification',
            name='photo_back',
            field=models.ImageField(upload_to='verifi'),
        ),
        migrations.AlterField(
            model_name='verification',
            name='photo_front',
            field=models.ImageField(upload_to='verifi'),
        ),
    ]
