# Generated by Django 3.2.7 on 2021-11-08 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_auto_20211107_0727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileinfo',
            name='language',
            field=models.CharField(choices=[('English', 'English'), ('French', 'French'), ('Bilingual', 'Bilingual')], max_length=30),
        ),
        migrations.AlterField(
            model_name='profilepersonal',
            name='account_type',
            field=models.CharField(blank=True, choices=[('tutor', 'Tutor'), ('learner', 'Learner')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='end_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
