# Generated by Django 3.2.6 on 2021-08-08 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_alter_tutorprofile_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorprofile',
            name='section',
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='language',
            field=models.CharField(choices=[('English', 'English'), ('French', 'French'), ('Others', 'Others')], default=1, max_length=30),
        ),
    ]
