# Generated by Django 3.2.7 on 2022-01-25 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_profilepersonal_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilepersonal',
            name='address',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
