# Generated by Django 3.2.7 on 2022-02-05 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_alter_profilepersonal_level_of_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='hour',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
