# Generated by Django 3.2.7 on 2022-02-05 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_hour_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hour',
            name='time',
        ),
    ]
