# Generated by Django 3.2.7 on 2022-02-06 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0015_remove_hour_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='level',
            field=models.CharField(blank=True, choices=[('Nursery', 'Nursery'), ('Primary', 'Primary'), ('Secondary', 'Secondary'), ('High School', 'High School'), ('University', 'University'), ('Others', 'Others')], max_length=30, null=True),
        ),
    ]
