# Generated by Django 3.2.7 on 2022-02-06 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0016_subject_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='level',
        ),
    ]
