# Generated by Django 3.2.6 on 2021-08-15 13:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
        ('review', '0002_auto_20210815_1405'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0017_alter_profile_date_of_birth'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('English', 'English'), ('French', 'French'), ('Others', 'Others')], default=1, max_length=30)),
                ('bio', models.TextField(blank=True, null=True)),
                ('experience', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProfilePersonal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(blank=True, choices=[('tutor', "i'm a tutor"), ('student', "i'm a Student"), ('parent', "i'm a Parent")], max_length=10, null=True)),
                ('title', models.CharField(blank=True, choices=[('mr', 'Mr'), ('mrs', 'Mrs'), ('miss', 'Miss'), ('ms', 'Ms'), ('dr', 'Dr'), ('prof', 'Prof')], max_length=10, null=True)),
                ('first_name', models.CharField(blank=True, max_length=30, null=True)),
                ('last_name', models.CharField(blank=True, max_length=30, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('quater', models.CharField(max_length=50, null=True)),
                ('level_of_education', models.CharField(blank=True, choices=[('Bachelor Degree(Bac +3)', 'Bachelor Degree'), ('Master Degree(Bac +5)', 'Master Degree'), ('Advanced Level(Bac)', 'Advanced Level'), ('Doctorate', 'Doctorate'), ('HND', 'HND'), ('Others', 'Others')], max_length=50, null=True)),
                ('date_of_birth', models.DateField(default=django.utils.timezone.now)),
                ('profile_pic', models.ImageField(default='media/default.png', upload_to='profile_img')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.city')),
                ('country', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='location.country')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.region')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.RemoveField(
            model_name='tutorprofile',
            name='category',
        ),
        migrations.RemoveField(
            model_name='tutorprofile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='tutorprofile',
            name='country',
        ),
        migrations.RemoveField(
            model_name='tutorprofile',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='tutorprofile',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='tutorprofile',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='tutorprofile',
            name='region',
        ),
        migrations.RemoveField(
            model_name='tutorprofile',
            name='sub_category',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='TutorProfile',
        ),
        migrations.AddField(
            model_name='profileinfo',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mainapp.profilepersonal'),
        ),
    ]
