# Generated by Django 3.2.6 on 2021-08-15 13:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('location', '0001_initial'),
        ('mainapp', '0018_auto_20210815_1405'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileinfo',
            name='profile',
        ),
        migrations.AddField(
            model_name='profileinfo',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profilepersonal',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='location.city'),
        ),
        migrations.AlterField(
            model_name='profilepersonal',
            name='region',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='location.region'),
        ),
    ]
