# Generated by Django 3.2.7 on 2022-03-05 08:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0020_privacy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilepersonal',
            name='favourite',
        ),
        migrations.AddField(
            model_name='profilepersonal',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='saved_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
