# Generated by Django 3.2.6 on 2021-08-15 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0020_alter_profileinfo_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileinfo',
            name='user',
        ),
        migrations.AddField(
            model_name='profileinfo',
            name='profile',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.profilepersonal'),
        ),
    ]
