# Generated by Django 3.2.6 on 2021-08-15 13:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0021_auto_20210815_1421'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileinfo',
            name='profile',
        ),
        migrations.AddField(
            model_name='profileinfo',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
