# Generated by Django 3.2.7 on 2022-03-05 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0021_auto_20220305_0953'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilepersonal',
            old_name='like',
            new_name='favourite',
        ),
    ]
