# Generated by Django 3.2.7 on 2022-03-13 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0023_auto_20220312_1840'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onlinelesson',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='onlinelesson',
            name='lesson',
        ),
        migrations.AddField(
            model_name='onlinelesson',
            name='booked',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.booked'),
        ),
        migrations.CreateModel(
            name='LessonPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('payment_method', models.CharField(blank=True, choices=[('MTN Mobile Money', 'MTN Mobile Money'), ('Orange Money', 'Orange Money')], max_length=255, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mainapp.onlinelesson')),
            ],
        ),
    ]
