# Generated by Django 3.2.6 on 2021-08-20 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
        ('mainapp', '0023_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilepersonal',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='location.subregion'),
        ),
        migrations.AddField(
            model_name='profilepersonal',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'male'), ('female', 'female')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='profilepersonal',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='location.city'),
        ),
        migrations.AlterField(
            model_name='profilepersonal',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='location.country'),
        ),
        migrations.AlterField(
            model_name='profilepersonal',
            name='region',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='location.region'),
        ),
    ]
