# Generated by Django 3.2.7 on 2022-03-13 08:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0024_auto_20220313_0918'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlinelesson',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_11', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='onlinelesson',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_22', to=settings.AUTH_USER_MODEL),
        ),
    ]
