# Generated by Django 3.2.6 on 2021-08-21 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
        ('mainapp', '0025_alter_profilepersonal_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilepersonal',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='location.country'),
        ),
    ]
