# Generated by Django 3.2.6 on 2021-08-21 11:44

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
        ('mainapp', '0026_alter_profilepersonal_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilepersonal',
            name='city',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='subregion', chained_model_field='subregion', on_delete=django.db.models.deletion.CASCADE, to='location.city'),
        ),
        migrations.AlterField(
            model_name='profilepersonal',
            name='division',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='region', chained_model_field='region', on_delete=django.db.models.deletion.CASCADE, to='location.subregion'),
        ),
    ]
