# Generated by Django 3.2.6 on 2021-08-21 11:45

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
        ('mainapp', '0027_auto_20210821_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilepersonal',
            name='city',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='division', chained_model_field='subregion', on_delete=django.db.models.deletion.CASCADE, to='location.city'),
        ),
    ]
