# Generated by Django 3.2.7 on 2022-03-13 09:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0027_auto_20220313_0958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onlinelesson',
            name='booked',
        ),
        migrations.AddField(
            model_name='lessonpayment',
            name='complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='onlinelesson',
            name='is_confirm',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='onlinelesson',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='onlinelesson',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tutor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Booked',
        ),
    ]
