# Generated by Django 3.2.7 on 2022-03-13 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0030_alter_onlinelesson_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlinelesson',
            name='is_seen',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='onlinelesson',
            name='mode',
            field=models.CharField(blank=True, choices=[('Video', 'Video'), ('Audio', 'Audio'), ('Chat', 'Chat')], max_length=255, null=True),
        ),
    ]
