# Generated by Django 3.2.7 on 2022-03-13 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0031_auto_20220313_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlinelesson',
            name='is_decline',
            field=models.BooleanField(default=False),
        ),
    ]
