# Generated by Django 3.2.6 on 2021-08-21 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0031_auto_20210821_1250'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilepersonal',
            old_name='quater',
            new_name='address_1',
        ),
        migrations.RemoveField(
            model_name='profilepersonal',
            name='city',
        ),
        migrations.RemoveField(
            model_name='profilepersonal',
            name='subregion',
        ),
        migrations.AddField(
            model_name='profilepersonal',
            name='address_2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
