# Generated by Django 3.2.6 on 2021-08-21 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0032_auto_20210821_1329'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='charger',
            new_name='charge',
        ),
    ]
