# Generated by Django 3.2.7 on 2022-03-15 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0032_onlinelesson_is_decline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlinelesson',
            name='end',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='onlinelesson',
            name='start',
            field=models.DateTimeField(),
        ),
    ]
