# Generated by Django 3.2.6 on 2021-08-21 13:26

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_subject'),
        ('mainapp', '0033_rename_charger_subject_charge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='subcategory',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='category', chained_model_field='category', on_delete=django.db.models.deletion.CASCADE, related_name='user_subcategory', to='category.subcategory'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='subcategory', chained_model_field='subcategory', on_delete=django.db.models.deletion.CASCADE, related_name='user_subject', to='category.subject'),
        ),
    ]
