# Generated by Django 3.2.7 on 2022-03-15 07:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0033_auto_20220315_0801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlinelesson',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 15, 7, 2, 36, 679124, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='onlinelesson',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 15, 7, 2, 36, 679124, tzinfo=utc)),
        ),
    ]
