# Generated by Django 3.2.7 on 2022-03-15 07:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0034_auto_20220315_0802'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlinelesson',
            name='is_cancel',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='onlinelesson',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 15, 7, 7, 23, 334022, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='onlinelesson',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 15, 7, 7, 23, 334022, tzinfo=utc)),
        ),
    ]
