# Generated by Django 3.2.7 on 2022-03-20 22:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0035_auto_20220315_0807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlinelesson',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 20, 22, 49, 29, 45710, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='onlinelesson',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 20, 22, 49, 29, 45710, tzinfo=utc)),
        ),
    ]
