# Generated by Django 3.2.6 on 2021-08-22 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
        ('mainapp', '0035_rename_target_subject_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilepersonal',
            name='country',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.PROTECT, to='location.country'),
        ),
        migrations.AlterField(
            model_name='profilepersonal',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10, null=True),
        ),
    ]
