# Generated by Django 3.2.7 on 2022-03-22 19:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0036_auto_20220320_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlinelesson',
            name='end',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='onlinelesson',
            name='start',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
