# Generated by Django 3.2.6 on 2021-08-22 09:05

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
        ('mainapp', '0037_alter_profilepersonal_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilepersonal',
            name='region',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='country', chained_model_field='country', default=1, on_delete=django.db.models.deletion.CASCADE, to='location.region'),
        ),
    ]
