# Generated by Django 3.2.13 on 2022-05-30 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0038_auto_20220407_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlinelesson',
            name='amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
