# Generated by Django 3.2.6 on 2021-08-23 15:59

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
        ('mainapp', '0038_alter_profilepersonal_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilepersonal',
            name='city',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='region', chained_model_field='region', default=1, on_delete=django.db.models.deletion.CASCADE, to='location.city'),
        ),
    ]
