# Generated by Django 3.2.13 on 2022-05-30 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0039_onlinelesson_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileinfo',
            name='amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
