# Generated by Django 3.2.13 on 2022-05-30 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0040_alter_profileinfo_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlinelesson',
            name='mode',
            field=models.CharField(blank=True, choices=[('Video', 'Video'), ('Audio', 'Audio')], max_length=255, null=True),
        ),
    ]
