# Generated by Django 3.2.13 on 2022-05-30 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0041_alter_onlinelesson_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlinelesson',
            name='mode',
            field=models.CharField(choices=[('Video', 'Video'), ('Audio', 'Audio')], max_length=255),
        ),
    ]
