# Generated by Django 3.2.13 on 2022-06-01 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0044_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonescrow',
            name='amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lessonescrow',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('MTN Mobile Money', 'MTN Mobile Money'), ('Orange Money', 'Orange Money')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='lessonescrow',
            name='lesson',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mainapp.onlinelesson'),
        ),
        migrations.DeleteModel(
            name='LessonPayment',
        ),
    ]
