# Generated by Django 3.2.13 on 2022-06-02 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0045_auto_20220601_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlinelesson',
            name='is_compelte',
            field=models.BooleanField(default=False),
        ),
    ]
