# Generated by Django 3.2.13 on 2022-06-04 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0047_lessonescrow_payout_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonescrow',
            name='amount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
