# Generated by Django 3.2.13 on 2022-06-04 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0048_alter_lessonescrow_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonescrow',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='onlinelesson',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
