# Generated by Django 3.2.13 on 2022-06-04 09:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0049_auto_20220604_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonescrow',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='EarnSpend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earn', models.IntegerField(default=0)),
                ('spend', models.IntegerField(default=0)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
