# Generated by Django 3.2.6 on 2021-09-03 15:00

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0050_auto_20210903_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilepersonal',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profileinfo',
            name='bio',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profileinfo',
            name='experience',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
