# Generated by Django 3.2.13 on 2022-06-04 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0050_auto_20220604_1013'),
    ]

    operations = [
        migrations.RenameField(
            model_name='onlinelesson',
            old_name='is_compelte',
            new_name='is_complete',
        ),
    ]
