# Generated by Django 3.2.13 on 2022-06-04 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0051_rename_is_compelte_onlinelesson_is_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='upgrade',
            name='escrow_payment',
            field=models.BooleanField(default=False),
        ),
    ]
