# Generated by Django 3.2.6 on 2021-09-04 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0051_auto_20210903_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='verification',
            name='status',
            field=models.CharField(choices=[('complete', 'complete'), ('in progess', 'in progress'), ('canceled', 'canceled')], default='in progess', max_length=50),
        ),
        migrations.AlterField(
            model_name='profileinfo',
            name='language',
            field=models.CharField(choices=[('English', 'English'), ('French', 'French'), ('Others', 'Others')], max_length=30),
        ),
        migrations.AlterField(
            model_name='verification',
            name='photo_back',
            field=models.ImageField(default='media/default.png', upload_to='verification/'),
        ),
        migrations.AlterField(
            model_name='verification',
            name='photo_front',
            field=models.ImageField(default='media/default.png', upload_to='verification/'),
        ),
    ]
