# Generated by Django 3.2.6 on 2021-09-04 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0052_auto_20210904_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verification',
            name='photo_back',
            field=models.ImageField(default='media/default.png', upload_to='verifi'),
        ),
        migrations.AlterField(
            model_name='verification',
            name='photo_front',
            field=models.ImageField(default='media/default.png', upload_to='verifi'),
        ),
        migrations.AlterField(
            model_name='verification',
            name='status',
            field=models.CharField(choices=[('complete', 'complete'), ('in progress', 'in progress'), ('canceled', 'canceled')], default='in progress', max_length=50),
        ),
    ]
