# Generated by Django 3.2.6 on 2021-09-04 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0053_auto_20210904_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verification',
            name='status',
            field=models.CharField(choices=[('complete', 'complete'), ('in progress', 'in progress'), ('canceled', 'canceled')], max_length=50),
        ),
    ]
