# Generated by Django 3.2.13 on 2022-06-29 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0053_auto_20220607_1539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upgrade',
            name='user',
        ),
        migrations.AlterField(
            model_name='profilepersonal',
            name='account_type',
            field=models.CharField(blank=True, choices=[('tutor', 'tutor'), ('learner', 'learner'), ('parent', 'parent')], max_length=10, null=True),
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='Upgrade',
        ),
    ]
