# Generated by Django 3.2.6 on 2021-09-04 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0054_alter_verification_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileinfo',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profileinfo',
            name='experience',
            field=models.TextField(blank=True, null=True),
        ),
    ]
