# Generated by Django 3.2.6 on 2021-09-06 14:33

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0055_auto_20210904_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='booked',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 6, 14, 33, 10, 195155, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='profilepersonal',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=False)),
                ('payment_method', models.CharField(choices=[('MTN Mobile Momey', 'mtn'), ('Orange Money', 'orange money'), ('YUP', 'yup'), ('VISA', 'visa')], max_length=40)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
