# Generated by Django 3.2.13 on 2022-12-08 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0056_billingpayment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccountHistory',
        ),
    ]
