# Generated by Django 3.2.6 on 2021-09-07 06:38

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0009_auto_20210822_1459'),
        ('mainapp', '0057_alter_booked_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileinfo',
            name='amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profileinfo',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_category', to='category.category'),
        ),
        migrations.AddField(
            model_name='profileinfo',
            name='charge',
            field=models.CharField(blank=True, choices=[('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('Hourly', 'Hourly')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='profileinfo',
            name='level',
            field=models.CharField(blank=True, choices=[('Nursery', 'Nursery'), ('Primary', 'Primary'), ('Secondary', 'Secondary'), ('High School', 'High School'), ('University', 'University'), ('Others', 'Others')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='profileinfo',
            name='subcategory',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='category', chained_model_field='category', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_subcategory', to='category.subcategory'),
        ),
        migrations.AddField(
            model_name='profileinfo',
            name='subject',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='subcategory', chained_model_field='subcategory', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_subject', to='category.subject'),
        ),
    ]
