# Generated by Django 3.2.6 on 2021-09-20 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0058_auto_20210907_0738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileinfo',
            name='level',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='level',
        ),
    ]
