# Generated by Django 3.2.7 on 2021-09-27 11:57

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0059_auto_20210920_0421'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', ckeditor.fields.RichTextField()),
                ('mission', ckeditor.fields.RichTextField()),
                ('goal', ckeditor.fields.RichTextField()),
                ('bg', models.ImageField(blank=True, null=True, upload_to='bg_img')),
            ],
        ),
        migrations.CreateModel(
            name='OurTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('title', models.CharField(max_length=256)),
                ('pic', models.ImageField(blank=True, null=True, upload_to='tram_img')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
