# Generated by Django 3.2.7 on 2021-10-02 13:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0064_auto_20211001_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upgrade',
            name='payment_method',
            field=models.CharField(choices=[('MTN Mobile Money', 'MTN Mobile Money'), ('Orange Money', 'Orange Money')], max_length=40),
        ),
        migrations.AlterField(
            model_name='upgrade',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
