# Generated by Django 3.2.7 on 2021-10-02 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0065_auto_20211002_1422'),
    ]

    operations = [
        migrations.CreateModel(
            name='HowToUse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='how_img')),
                ('how_text', models.TextField()),
            ],
        ),
    ]
