# Generated by Django 3.2.7 on 2021-10-03 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0067_auto_20211003_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='upgrade',
            name='code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='upgrade',
            name='external_ref',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='upgrade',
            name='operator',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='upgrade',
            name='operator_ref',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='upgrade',
            name='reason',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='upgrade',
            name='reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='upgrade',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
