# Generated by Django 3.2.7 on 2021-10-05 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0068_auto_20211003_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmedia',
            name='github',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='socialmedia',
            name='twitter',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
