# Generated by Django 3.2.7 on 2021-10-07 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0071_rename_profileview_profileviewed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profileviewed',
            old_name='user_by',
            new_name='viewed_by',
        ),
    ]
