# Generated by Django 3.2.7 on 2021-10-10 12:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0074_profilepersonal_favourite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilepersonal',
            name='favourite',
            field=models.ManyToManyField(related_name='saved_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
