# Generated by Django 3.2.7 on 2021-10-10 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0077_auto_20211010_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileinfo',
            name='charge',
            field=models.CharField(blank=True, choices=[('Week', 'Weekly'), ('Month', 'Monthly'), ('Hour', 'Hourly')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='charge',
            field=models.CharField(blank=True, choices=[('Week', 'Weekly'), ('Month', 'Monthly'), ('Hour', 'Hourly')], max_length=30, null=True),
        ),
    ]
