# Generated by Django 3.2.13 on 2022-09-20 00:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0002_message'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChatRoom',
            new_name='UserRoom',
        ),
    ]
