# Generated by Django 3.2.13 on 2022-09-20 01:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0004_auto_20220920_0238'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PersonalRooms',
            new_name='PersonalRoom',
        ),
    ]
