# Generated by Django 3.2.6 on 2021-08-08 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_auto_20210808_1020'),
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='section',
        ),
        migrations.DeleteModel(
            name='Section',
        ),
    ]
