# Generated by Django 3.2.6 on 2021-08-22 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='category_image'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='subcategory_image'),
        ),
        migrations.AddField(
            model_name='subject',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='subject_image'),
        ),
    ]
