# Generated by Django 3.2.6 on 2021-08-22 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0006_auto_20210822_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(default='default.png', upload_to='category_image'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='image',
            field=models.ImageField(default='default.png', upload_to='subcategory_image'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='image',
            field=models.ImageField(default='default.png', upload_to='subject_image'),
        ),
    ]
