# Generated by Django 3.2.6 on 2021-08-26 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0040_experience_qualification'),
        ('review', '0003_auto_20210826_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_profile', to='mainapp.profilepersonal'),
        ),
    ]
