# Generated by Django 3.2.6 on 2021-08-08 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='from_user',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='post',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='review',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='thread',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='to_user',
        ),
        migrations.RemoveField(
            model_name='threadmodel',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='threadmodel',
            name='user',
        ),
        migrations.DeleteModel(
            name='MessageModel',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='ThreadModel',
        ),
    ]
